### ISSUE TITLE
Scan foods flow

### ISSUE THREAD

**Issue by marinPassio** [Passiolife/Flutter-Nutrition-AI-Module#10]
- [x] Onboarding view
- [x] Result view with Edit and Log buttons
- [x] Item Added to Diary view
- [x] Barcode not recognised view
- [ ]  Nutrition facts scanner (not yet implemented in the Flutter SDK

**Comment by Loenike** [comment]
follow up ticket on Nutrition Facts here:
https://github.com/Passiolife/Flutter-Nutrition-AI-Demo/issues/67
