### ISSUE TITLE
Refactor the v3 FoodRecord

### ISSUE THREAD

**Issue by marinPassio** [Passiolife/Flutter-Nutrition-AI-Module#13]
[iOS Food Record](https://github.com/Passiolife/iOS-Demo-App/blob/Feature/V3.0.1UI/MasterModule/NutritionDataStructure/FoodRecordV3.swift)
[Android Food Record](https://github.com/Passiolife/Android-Passio-SDK/blob/3.0.0/PassioSDKDemo/passio-ui-module/src/main/java/ai/passio/nutrition/uimodule/ui/model/FoodRecord.kt)

**Comment by sahilmind** [comment]
@marinPassio I am unable to access the [iOS Food Record](https://github.com/Passiolife/iOS-Demo-App/blob/Feature/V3.0.1UI/MasterModule/NutritionDataStructure/FoodRecordV3.swift) source code. Could you grant me access to the **iOS-Demo-App** so I can review the implementation? Currently I am replicating what's done in Android. While reviewing the nutrientsSelectedSize() method in FoodRecordIngredient.kt I found it uses the referenceNutrients constructor. You suggested implementing only two constructors within the SDK but the mentioned constructor is not implemented on the Flutter side.

**Comment by marinPassio** [comment]
@sahilmind Let's add that constructor as well. You should have access now to the iOS-Demo-App repo
