### ISSUE TITLE
Flutter Edit Screen Fixes

### ISSUE THREAD

**Issue by Loenike** [Passiolife/Flutter-Nutrition-AI-Module#17]
- We display open food facts link on all foods (e.g. search "Lemonade Target") - that food is not from open food facts. or Coffee, brewed
- The Open Food Facts link is not clickable. please see iOS for reference implementation

![IMG_9314](https://github.com/Passiolife/Flutter-Nutrition-AI-Module/assets/30158346/855167d5-2fc6-4985-87cd-fa37f005a2fc)

**Comment by sahilmind** [comment]
This is in the backlog. We're prioritizing SDK 3.0 release now. We'll tackle this later. 
CC: @marinPassio

**Comment by Loenike** [comment]
@sahilmind @marinPassio sounds good!

just wanted to make sure that we are not incorrectly pulling info from Open Food Facts on the SDK. but if it's just a demo app issue, then we can address later for sure

**Comment by Loenike** [comment]
all addressed
