### ISSUE TITLE
User profile screen

### ISSUE THREAD

**Issue by marinPassio** [Passiolife/Flutter-Nutrition-AI-Module#18]
Add the following features from the user profile screen:

- [x] Personal information
- [x] Nutrition goals
- [x] Daily nutrition target graph with the input dialog
- [x] Calculated BMI graph
- [x] Settings screen with the ability to change units for user profile and enable reminder notifications

**Comment by sahilmind** [comment]
Discuss user profile logic in the iOS Demo App here: [User Profile Logic discussion](https://github.com/Passiolife/iOS-Demo-App/issues/361)
