### ISSUE TITLE
Progress screen

### ISSUE THREAD

**Issue by marinPassio** [Passiolife/Flutter-Nutrition-AI-Module#19]
- [x] Create calories and macro charts for the currently selected week/month
- [x] Create a list of micro nutrients with the consumed values and remaining values depicted in a horizontal chart
- [x] Leave out the generate report button as it's not yet needed

**Comment by sahilmind** [comment]
@marinPassio As discussed all nutrients with recommended values are already on the nutrition information screen. The remaining blank nutrients need recommended values and default symbols.

CC: @chiragramimi @nikunj-MindInventory @akashmi

| Nutrient | Recommended Value | Symbol |
| :---: | :---: | :---: |
| Saturated Fat     |    20     | g |
| Trans Fat     |    2.2     | g |
| Cholesterol     |    300     | mg |
| Sodium     |    2300     | mg |
| Dietary Fiber     |    28     | g |
| Total Sugar     |    50     | g |
| Vitamin D     |    20     | µg |
| Calcium     |    1000     | mg |
| Iron     |    18     | mg |
| Potassium     |    4700     | mg |
| Polyunsaturated Fat     |    22     | g |
| Monounsaturated Fat    |    44     | g |
| Magnesium    |    420     | mg |
| Iodine    |    150     | µg |
| Vitamin B6    |    1.7     | mg |
| Vitamin B12    |    2.4     | µg |
| Vitamin E    |    15     | mg |
| Vitamin A    |    3000     | iu |
| Vitamin C    |    90     | µg |
| Zinc    |    10     | mg |
| Selenium    |    55     | µg |
| Folic Acid    |    400     | µg |
| Chromium    |    35     | µg |
| Added Sugar     |  50  | g  |
| Alcohol     |        |   |
| Phosphorus     |        |   |
| Alcohol Sugar     |       |   |
| Added Vitamin B12    |        |   |
| Added Vitamin E    |        |   |
| ~~Vitamin K Phylloquinone~~ |        |   |
| ~~Vitamin K Menaquinone4~~    |        |   |
| ~~Vitamin K Dihydrophylloquinone~~    |        |   |
